# Generated by Django 4.2 on 2023-05-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_room_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='content',
        ),
    ]
