# Generated by Django 4.2 on 2023-05-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_remove_room_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
