# Generated by Django 4.2 on 2023-05-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_room_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='content',
            field=models.TextField(blank=True, default='\ndef main():\n    # Your code goes here\n    print("Hello, world!")\n\nif __name__ == "__main__":\n    main()\n'),
        ),
    ]
